import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>PAGE TITLE</h1>

      <p>PLACEHOLDER paragraph</p>
      <Link href="/AI">
        <a>To AI</a>
      </Link>
    </div>
  );
};

export default Home;
